# Generation of Kubernetes YAML is still under development!
#
# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-2.2.1
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2021-01-30T17:14:08Z"
  labels:
    app: wordpress-testing
  name: wordpress-testing
spec:
  containers:
  - command:
    - mysqld
    env:
    - name: PATH
      value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    - name: TERM
      value: xterm
    - name: container
      value: podman
    - name: MYSQL_PASSWORD
      value: 1maGazine!
    - name: MYSQL_USER
      value: magazine
    - name: MYSQL_DATABASE
      value: magazine
    - name: GOSU_VERSION
      value: "1.12"
    - name: GPG_KEYS
      value: 177F4010FE56CA3336300305F1656F24C74CD1D8
    - name: MARIADB_MAJOR
      value: "10.5"
    - name: MARIADB_VERSION
      value: 1:10.5.8+maria~focal
    - name: MYSQL_ROOT_PASSWORD
      value: 1maGazine!
    - name: HOSTNAME
    image: docker.io/library/mariadb:10.5
    name: wordpress-testingdb1
    ports:
    - containerPort: 3306
      hostPort: 6603
      protocol: TCP
    - containerPort: 80
      hostPort: 8080
      protocol: TCP
    resources: {}
    securityContext:
      allowPrivilegeEscalation: true
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
      privileged: false
      readOnlyRootFilesystem: false
      seLinuxOptions: {}
    volumeMounts:
    - mountPath: /var/lib/mysql
      name: home-franckf-.local-share-containers-storage-volumes-wordpress-testing_wpdbvol-_data
    workingDir: /
  - command:
    - apache2-foreground
    env:
    - name: PATH
      value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    - name: TERM
      value: xterm
    - name: container
      value: podman
    - name: PHP_CPPFLAGS
      value: -fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64
    - name: PHP_SHA256
      value: f9f3c37969fcd9006c1dbb1dd76ab53f28c698a1646fa2dde8547c3f45e02886
    - name: APACHE_CONFDIR
      value: /etc/apache2
    - name: PHP_EXTRA_BUILD_DEPS
      value: apache2-dev
    - name: WORDPRESS_DB_USER
      value: magazine
    - name: PHP_INI_DIR
      value: /usr/local/etc/php
    - name: PHP_CFLAGS
      value: -fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64
    - name: WORDPRESS_DB_NAME
      value: magazine
    - name: APACHE_ENVVARS
      value: /etc/apache2/envvars
    - name: PHP_URL
      value: https://www.php.net/distributions/php-7.4.14.tar.xz
    - name: WORDPRESS_DB_PASSWORD
      value: 1maGazine!
    - name: GPG_KEYS
      value: 42670A7FE4D0441C8E4632349E4FDC074A4EF02D 5A52880781F755608BF815FC910DEB46F53EA312
    - name: PHPIZE_DEPS
      value: "autoconf \t\tdpkg-dev \t\tfile \t\tg++ \t\tgcc \t\tlibc-dev \t\tmake \t\tpkg-config \t\tre2c"
    - name: WORDPRESS_DB_HOST
      value: db
    - name: WORDPRESS_TABLE_PREFIX
      value: cz
    - name: PHP_EXTRA_CONFIGURE_ARGS
      value: --with-apxs2 --disable-cgi
    - name: PHP_LDFLAGS
      value: -Wl,-O1 -pie
    - name: PHP_VERSION
      value: 7.4.14
    - name: PHP_ASC_URL
      value: https://www.php.net/distributions/php-7.4.14.tar.xz.asc
    - name: HOSTNAME
    image: docker.io/library/wordpress:latest
    name: wordpress-testingweb1
    resources: {}
    securityContext:
      allowPrivilegeEscalation: true
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
      privileged: false
      readOnlyRootFilesystem: false
      seLinuxOptions: {}
    volumeMounts:
    - mountPath: /var/www/html
      name: home-franckf-.local-share-containers-storage-volumes-wordpress-testing_wordpress-_data
    workingDir: /var/www/html
  restartPolicy: Never
  volumes:
  - hostPath:
      path: /home/franckf/.local/share/containers/storage/volumes/wordpress-testing_wpdbvol/_data
      type: Directory
    name: home-franckf-.local-share-containers-storage-volumes-wordpress-testing_wpdbvol-_data
  - hostPath:
      path: /home/franckf/.local/share/containers/storage/volumes/wordpress-testing_wordpress/_data
      type: Directory
    name: home-franckf-.local-share-containers-storage-volumes-wordpress-testing_wordpress-_data
status: {}
---
metadata:
  creationTimestamp: null
spec: {}
status:
  loadBalancer: {}

